apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: myweb-svc
spec:
 selector:
   # Selector for Pods
   app: myweb
 ports:
   # Port Map
 - port: 8081
   targetPort: 80
   protocol: TCP
 type: LoadBalancer